[package]
name = "launchio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-fuzzy-search = "0.1.1"
fltk = { version = "^1.4", git = "https://github.com/fltk-rs/fltk-rs" }
dirs = "3.0"
